### ISSUE TITLE
Detecting extension to undefined rule

### ISSUE THREAD

**Issue by dontcallmedom** [hildjj/node-abnf#10]
https://github.com/hildjj/node-abnf/commit/06478c7f74c06cc63d515cb5dccfcce5e30bfc4b#diff-addae5784ef2ffba0f8c8f5c55735cb3c20be979c7b4fcec66ca8c3fdd134172 made it that extending a rule with `=/` but for an undefined term stopped from throwing but instead create a new rule from scratch.

This makes it impossible to use the parser to detect a ruleset that has gaps.

Was there a particular motivation for no longer throwing? any suggestion on how to make it possible to detect such a situation?

**Comment by hildjj** [comment]
It's been a long time since I looked at this code.  My local repo has some pending changes that I'll try to understand, but it looks like they may be in this area.

**Comment by dontcallmedom** [comment]
I think a minimal test case would be:
```anbf
extended-definition  =/ ""
```
right now, the parser happily takes it by essentially interpreting as `extended-definition  = ""`; that's probably a useful behaviour in some circumstances, but it would be nice to be able to to detect it when using it for validation purposes.

Thanks much for looking into this (and for the very powerful library overall)!

**Comment by hildjj** [comment]
Oh.  I see your point.  I was probably working on an ABNF that extended something else without my realizing it.  [rfc5234](https://datatracker.ietf.org/doc/html/rfc5234#section-3.3) doesn't have adequate requirements language for my taste, but the example clearly shows that you should have an `=` before `=/`.  I'll add some checks back in.

**Comment by hildjj** [comment]
Fix blocked on resolution for #9, then a rebase.

**Comment by hildjj** [comment]
I think I've got this fixed in head, if you'd like to test before I publish v3?

**Comment by dontcallmedom** [comment]
That indeed fixes it - thanks a bunch
